services:
 db:
  container_name: universae_db
  image: postgres
  user: '1001'
  restart: always
  environment:
   POSTGRES_PASSWORD: easrevinu
   POSTGRES_USER: universae
   POSTGRES_DB: universae
   PGDATA: /var/lib/postgresql/data/universae
  volumes:
   - ${PWD}/etc/infrastructure/db-data:/var/lib/postgresql/data
  ports:
   - '5432:5432'
  networks:
   - universae-network

 mail:
  container_name: universae_mail
  image: maildev/maildev
  environment:
   MAILDEV_OUTGOING_USER: "${FROM_EMAIL}"
   MAILDEV_OUTGOING_PASS: "${FROM_EMAIL_PASS}"
  ports:
   - "1025:1025"
   - "1080:1080"
  networks:
   - universae-network

networks:
 universae-network:
  external: true
