export enum TimeZoneEnum {
  GMT = 'GMT',
  GMT_PLUS_1 = 'GMT+1',
  GMT_PLUS_2 = 'GMT+2',
  GMT_PLUS_3 = 'GMT+3',
  GMT_PLUS_4 = 'GMT+4',
  GMT_PLUS_5 = 'GMT+5',
  GMT_PLUS_6 = 'GMT+6',
  GMT_PLUS_7 = 'GMT+7',
  GMT_PLUS_8 = 'GMT+8',
  GMT_PLUS_9 = 'GMT+9',
  GMT_PLUS_10 = 'GMT+10',
  GMT_PLUS_11 = 'GMT+11',
  GMT_PLUS_12 = 'GMT+12',
}
