export const countries = [
  {
    ISO: 'AF',
    ISO3: 'AFG',
    name: 'Afganistán',
    phone_code: '+93',
    emoji_flag: '🇦🇫',
  },
  {
    ISO: 'DZ',
    ISO3: 'DZA',
    name: 'Argelia',
    phone_code: '+213',
    emoji_flag: '🇩🇿',
  },
  {
    ISO: 'AD',
    ISO3: 'AND',
    name: 'Andorra',
    phone_code: '+376',
    emoji_flag: '🇦🇩',
  },
  {
    ISO: 'AO',
    ISO3: 'AGO',
    name: 'Angola',
    phone_code: '+244',
    emoji_flag: '🇦🇴',
  },
  {
    ISO: 'AS',
    ISO3: 'ASM',
    name: 'Samoa Americana',
    phone_code: '+1-684',
    emoji_flag: '🇦🇸',
  },
  {
    ISO: 'AG',
    ISO3: 'ATG',
    name: 'Antigua y Barbuda',
    phone_code: '+1-268',
    emoji_flag: '🇦🇬',
  },
  {
    ISO: 'AR',
    ISO3: 'ARG',
    name: 'Argentina',
    phone_code: '+54',
    emoji_flag: '🇦🇷',
  },
  {
    ISO: 'AI',
    ISO3: 'AIA',
    name: 'Anguila',
    phone_code: '+1-264',
    emoji_flag: '🇦🇮',
  },
  {
    ISO: 'AM',
    ISO3: 'ARM',
    name: 'Armenia',
    phone_code: '+374',
    emoji_flag: '🇦🇲',
  },
  {
    ISO: 'AW',
    ISO3: 'ABW',
    name: 'Aruba',
    phone_code: '+297',
    emoji_flag: '🇦🇼',
  },
  {
    ISO: 'AU',
    ISO3: 'AUS',
    name: 'Australia',
    phone_code: '+61',
    emoji_flag: '🇦🇺',
  },
  {
    ISO: 'AT',
    ISO3: 'AUT',
    name: 'Austria',
    phone_code: '+43',
    emoji_flag: '🇦🇹',
  },
  {
    ISO: 'AZ',
    ISO3: 'AZE',
    name: 'Azerbaiyán',
    phone_code: '+994',
    emoji_flag: '🇦🇿',
  },
  {
    ISO: 'BS',
    ISO3: 'BHS',
    name: 'Bahamas',
    phone_code: '+1-242',
    emoji_flag: '🇧🇸',
  },
  {
    ISO: 'BH',
    ISO3: 'BHR',
    name: 'Baréin',
    phone_code: '+973',
    emoji_flag: '🇧🇭',
  },
  {
    ISO: 'BD',
    ISO3: 'BGD',
    name: 'Bangladés',
    phone_code: '+880',
    emoji_flag: '🇧🇩',
  },
  {
    ISO: 'BB',
    ISO3: 'BRB',
    name: 'Barbados',
    phone_code: '+1-246',
    emoji_flag: '🇧🇧',
  },
  {
    ISO: 'BY',
    ISO3: 'BLR',
    name: 'Bielorrusia',
    phone_code: '+375',
    emoji_flag: '🇧🇾',
  },
  {
    ISO: 'BE',
    ISO3: 'BEL',
    name: 'Bélgica',
    phone_code: '+32',
    emoji_flag: '🇧🇪',
  },
  {
    ISO: 'BZ',
    ISO3: 'BLZ',
    name: 'Belice',
    phone_code: '+501',
    emoji_flag: '🇧🇿',
  },
  {
    ISO: 'BJ',
    ISO3: 'BEN',
    name: 'Benín',
    phone_code: '+229',
    emoji_flag: '🇧🇯',
  },
  {
    ISO: 'BM',
    ISO3: 'BMU',
    name: 'Bermuda',
    phone_code: '+1-441',
    emoji_flag: '🇧🇲',
  },
  {
    ISO: 'BT',
    ISO3: 'BTN',
    name: 'Bután',
    phone_code: '+975',
    emoji_flag: '🇧🇹',
  },
  {
    ISO: 'BO',
    ISO3: 'BOL',
    name: 'Bolivia',
    phone_code: '+591',
    emoji_flag: '🇧🇴',
  },
  {
    ISO: 'BA',
    ISO3: 'BIH',
    name: 'Bosnia y Herzegovina',
    phone_code: '+387',
    emoji_flag: '🇧🇦',
  },
  {
    ISO: 'BW',
    ISO3: 'BWA',
    name: 'Botsuana',
    phone_code: '+267',
    emoji_flag: '🇧🇼',
  },
  {
    ISO: 'BR',
    ISO3: 'BRA',
    name: 'Brasil',
    phone_code: '+55',
    emoji_flag: '🇧🇷',
  },
  {
    ISO: 'IO',
    ISO3: 'IOT',
    name: 'Territorio Británico del Océano Índico',
    phone_code: '',
    emoji_flag: '🇮🇴',
  },
  {
    ISO: 'BN',
    ISO3: 'BRN',
    name: 'Brunei',
    phone_code: '+673',
    emoji_flag: '🇧🇳',
  },
  {
    ISO: 'BG',
    ISO3: 'BGR',
    name: 'Bulgaria',
    phone_code: '+359',
    emoji_flag: '🇧🇬',
  },
  {
    ISO: 'BF',
    ISO3: 'BFA',
    name: 'Burkina Faso',
    phone_code: '+226',
    emoji_flag: '🇧🇫',
  },
  {
    ISO: 'BI',
    ISO3: 'BDI',
    name: 'Burundi',
    phone_code: '+257',
    emoji_flag: '🇧🇮',
  },
  {
    ISO: 'KH',
    ISO3: 'KHM',
    name: 'Camboya',
    phone_code: '+855',
    emoji_flag: '🇰🇭',
  },
  {
    ISO: 'CM',
    ISO3: 'CMR',
    name: 'Camerún',
    phone_code: '+237',
    emoji_flag: '🇨🇲',
  },
  {
    ISO: 'CA',
    ISO3: 'CAN',
    name: 'Canadá',
    phone_code: '+1',
    emoji_flag: '🇨🇦',
  },
  {
    ISO: 'CV',
    ISO3: 'CPV',
    name: 'Cabo Verde',
    phone_code: '+238',
    emoji_flag: '🇨🇻',
  },
  {
    ISO: 'KY',
    ISO3: 'CYM',
    name: 'Islas Caimán',
    phone_code: '+1-345',
    emoji_flag: '🇰🇾',
  },
  {
    ISO: 'CF',
    ISO3: 'CAF',
    name: 'República Centroafricana',
    phone_code: '+236',
    emoji_flag: '🇨🇫',
  },
  {
    ISO: 'TD',
    ISO3: 'TCD',
    name: 'Chad',
    phone_code: '+235',
    emoji_flag: '🇹🇩',
  },
  {
    ISO: 'CL',
    ISO3: 'CHL',
    name: 'Chile',
    phone_code: '+56',
    emoji_flag: '🇨🇱',
  },
  {
    ISO: 'CN',
    ISO3: 'CHN',
    name: 'China',
    phone_code: '+86',
    emoji_flag: '🇨🇳',
  },
  {
    ISO: 'CX',
    ISO3: 'CXR',
    name: 'Isla de Navidad',
    phone_code: '+61',
    emoji_flag: '🇨🇽',
  },
  {
    ISO: 'CC',
    ISO3: 'CCK',
    name: 'Islas Cocos (Keeling)',
    phone_code: '+61',
    emoji_flag: '🇨🇨',
  },
  {
    ISO: 'CO',
    ISO3: 'COL',
    name: 'Colombia',
    phone_code: '+57',
    emoji_flag: '🇨🇴',
  },
  {
    ISO: 'KM',
    ISO3: 'COM',
    name: 'Comoras',
    phone_code: '+269',
    emoji_flag: '🇰🇲',
  },
  {
    ISO: 'CG',
    ISO3: 'COG',
    name: 'Congo',
    phone_code: '+242',
    emoji_flag: '🇨🇬',
  },
  {
    ISO: 'CD',
    ISO3: 'COD',
    name: 'República Democrática del Congo',
    phone_code: '+243',
    emoji_flag: '🇨🇩',
  },
  {
    ISO: 'CK',
    ISO3: 'COK',
    name: 'Islas Cook',
    phone_code: '+682',
    emoji_flag: '🇨🇰',
  },
  {
    ISO: 'CR',
    ISO3: 'CRI',
    name: 'Costa Rica',
    phone_code: '+506',
    emoji_flag: '🇨🇷',
  },
  {
    ISO: 'CI',
    ISO3: 'CIV',
    name: 'Costa de Marfil',
    phone_code: '+225',
    emoji_flag: '🇨🇮',
  },
  {
    ISO: 'HR',
    ISO3: 'HRV',
    name: 'Croacia',
    phone_code: '+385',
    emoji_flag: '🇭🇷',
  },
  {
    ISO: 'CU',
    ISO3: 'CUB',
    name: 'Cuba',
    phone_code: '+53',
    emoji_flag: '🇨🇺',
  },
  {
    ISO: 'CY',
    ISO3: 'CYP',
    name: 'Chipre',
    phone_code: '+357',
    emoji_flag: '🇨🇾',
  },
  {
    ISO: 'CZ',
    ISO3: 'CZE',
    name: 'Chequia',
    phone_code: '+420',
    emoji_flag: '🇨🇿',
  },
  {
    ISO: 'DK',
    ISO3: 'DNK',
    name: 'Dinamarca',
    phone_code: '+45',
    emoji_flag: '🇩🇰',
  },
  {
    ISO: 'DJ',
    ISO3: 'DJI',
    name: 'Yibuti',
    phone_code: '+253',
    emoji_flag: '🇩🇯',
  },
  {
    ISO: 'DM',
    ISO3: 'DMA',
    name: 'Dominica',
    phone_code: '+1-767',
    emoji_flag: '🇩🇲',
  },
  {
    ISO: 'DO',
    ISO3: 'DOM',
    name: 'República Dominicana',
    phone_code: '+1-809',
    emoji_flag: '🇩🇴',
  },
  {
    ISO: 'EC',
    ISO3: 'ECU',
    name: 'Ecuador',
    phone_code: '+593',
    emoji_flag: '🇪🇨',
  },
  {
    ISO: 'EG',
    ISO3: 'EGY',
    name: 'Egipto',
    phone_code: '+20',
    emoji_flag: '🇪🇬',
  },
  {
    ISO: 'SV',
    ISO3: 'SLV',
    name: 'El Salvador',
    phone_code: '+503',
    emoji_flag: '🇸🇻',
  },
  {
    ISO: 'GQ',
    ISO3: 'GNQ',
    name: 'Guinea Ecuatorial',
    phone_code: '+240',
    emoji_flag: '🇬🇶',
  },
  {
    ISO: 'ER',
    ISO3: 'ERI',
    name: 'Eritrea',
    phone_code: '+291',
    emoji_flag: '🇪🇷',
  },
  {
    ISO: 'EE',
    ISO3: 'EST',
    name: 'Estonia',
    phone_code: '+372',
    emoji_flag: '🇪🇪',
  },
  {
    ISO: 'ET',
    ISO3: 'ETH',
    name: 'Etiopía',
    phone_code: '+251',
    emoji_flag: '🇪🇹',
  },
  {
    ISO: 'FK',
    ISO3: 'FLK',
    name: 'Islas Malvinas',
    phone_code: '+500',
    emoji_flag: '🇫🇰',
  },
  {
    ISO: 'FO',
    ISO3: 'FRO',
    name: 'Islas Feroe',
    phone_code: '+298',
    emoji_flag: '🇫🇴',
  },
  {
    ISO: 'FJ',
    ISO3: 'FJI',
    name: 'Fiyi',
    phone_code: '+679',
    emoji_flag: '🇫🇯',
  },
  {
    ISO: 'FI',
    ISO3: 'FIN',
    name: 'Finlandia',
    phone_code: '+358',
    emoji_flag: '🇫🇮',
  },
  {
    ISO: 'FR',
    ISO3: 'FRA',
    name: 'Francia',
    phone_code: '+33',
    emoji_flag: '🇫🇷',
  },
  {
    ISO: 'GF',
    ISO3: 'GUF',
    name: 'Guayana Francesa',
    phone_code: '+594',
    emoji_flag: '🇬🇫',
  },
  {
    ISO: 'PF',
    ISO3: 'PYF',
    name: 'Polinesia Francesa',
    phone_code: '+689',
    emoji_flag: '🇵🇫',
  },
  {
    ISO: 'GA',
    ISO3: 'GAB',
    name: 'Gabón',
    phone_code: '+241',
    emoji_flag: '🇬🇦',
  },
  {
    ISO: 'GM',
    ISO3: 'GMB',
    name: 'Gambia',
    phone_code: '+220',
    emoji_flag: '🇬🇲',
  },
  {
    ISO: 'GE',
    ISO3: 'GEO',
    name: 'Georgia',
    phone_code: '+995',
    emoji_flag: '🇬🇪',
  },
  {
    ISO: 'DE',
    ISO3: 'DEU',
    name: 'Alemania',
    phone_code: '+49',
    emoji_flag: '🇩🇪',
  },
  {
    ISO: 'GH',
    ISO3: 'GHA',
    name: 'Ghana',
    phone_code: '+233',
    emoji_flag: '🇬🇭',
  },
  {
    ISO: 'GI',
    ISO3: 'GIB',
    name: 'Gibraltar',
    phone_code: '+350',
    emoji_flag: '🇬🇮',
  },
  {
    ISO: 'GR',
    ISO3: 'GRC',
    name: 'Grecia',
    phone_code: '+30',
    emoji_flag: '🇬🇷',
  },
  {
    ISO: 'GL',
    ISO3: 'GRL',
    name: 'Groenlandia',
    phone_code: '+299',
    emoji_flag: '🇬🇱',
  },
  {
    ISO: 'GD',
    ISO3: 'GRD',
    name: 'Granada',
    phone_code: '+1-473',
    emoji_flag: '🇬🇩',
  },
  {
    ISO: 'GP',
    ISO3: 'GLP',
    name: 'Guadalupe',
    phone_code: '+590',
    emoji_flag: '🇬🇵',
  },
  {
    ISO: 'GU',
    ISO3: 'GUM',
    name: 'Guam',
    phone_code: '+1-671',
    emoji_flag: '🇬🇺',
  },
  {
    ISO: 'GT',
    ISO3: 'GTM',
    name: 'Guatemala',
    phone_code: '+502',
    emoji_flag: '🇬🇹',
  },
  {
    ISO: 'GN',
    ISO3: 'GIN',
    name: 'Guinea',
    phone_code: '+224',
    emoji_flag: '🇬🇳',
  },
  {
    ISO: 'GW',
    ISO3: 'GNB',
    name: 'Guinea-Bisáu',
    phone_code: '+245',
    emoji_flag: '🇬🇼',
  },
  {
    ISO: 'GY',
    ISO3: 'GUY',
    name: 'Guyana',
    phone_code: '+592',
    emoji_flag: '🇬🇾',
  },
  {
    ISO: 'HT',
    ISO3: 'HTI',
    name: 'Haití',
    phone_code: '+509',
    emoji_flag: '🇭🇹',
  },
  {
    ISO: 'VA',
    ISO3: 'VAT',
    name: 'Santa Sede (Estado de la Ciudad del Vaticano)',
    phone_code: '+379',
    emoji_flag: '🇻🇦',
  },
  {
    ISO: 'HN',
    ISO3: 'HND',
    name: 'Honduras',
    phone_code: '+504',
    emoji_flag: '🇭🇳',
  },
  {
    ISO: 'HK',
    ISO3: 'HKG',
    name: 'Hong Kong',
    phone_code: '+852',
    emoji_flag: '🇭🇰',
  },
  {
    ISO: 'HU',
    ISO3: 'HUN',
    name: 'Hungría',
    phone_code: '+36',
    emoji_flag: '🇭🇺',
  },
  {
    ISO: 'IS',
    ISO3: 'ISL',
    name: 'Islandia',
    phone_code: '+354',
    emoji_flag: '🇮🇸',
  },
  {
    ISO: 'IN',
    ISO3: 'IND',
    name: 'India',
    phone_code: '+91',
    emoji_flag: '🇮🇳',
  },
  {
    ISO: 'ID',
    ISO3: 'IDN',
    name: 'Indonesia',
    phone_code: '+62',
    emoji_flag: '🇮🇩',
  },
  {
    ISO: 'IR',
    ISO3: 'IRN',
    name: 'Irán',
    phone_code: '+98',
    emoji_flag: '🇮🇷',
  },
  {
    ISO: 'IQ',
    ISO3: 'IRQ',
    name: 'Irak',
    phone_code: '+964',
    emoji_flag: '🇮🇶',
  },
  {
    ISO: 'IE',
    ISO3: 'IRL',
    name: 'Irlanda',
    phone_code: '+353',
    emoji_flag: '🇮🇪',
  },
  {
    ISO: 'IL',
    ISO3: 'ISR',
    name: 'Israel',
    phone_code: '+972',
    emoji_flag: '🇮🇱',
  },
  {
    ISO: 'IT',
    ISO3: 'ITA',
    name: 'Italia',
    phone_code: '+39',
    emoji_flag: '🇮🇹',
  },
  {
    ISO: 'JM',
    ISO3: 'JAM',
    name: 'Jamaica',
    phone_code: '+1-876',
    emoji_flag: '🇯🇲',
  },
  {
    ISO: 'JP',
    ISO3: 'JPN',
    name: 'Japón',
    phone_code: '+81',
    emoji_flag: '🇯🇵',
  },
  {
    ISO: 'JO',
    ISO3: 'JOR',
    name: 'Jordania',
    phone_code: '+962',
    emoji_flag: '🇯🇴',
  },
  {
    ISO: 'KZ',
    ISO3: 'KAZ',
    name: 'Kazajistán',
    phone_code: '+7',
    emoji_flag: '🇰🇿',
  },
  {
    ISO: 'KE',
    ISO3: 'KEN',
    name: 'Kenia',
    phone_code: '+254',
    emoji_flag: '🇰🇪',
  },
  {
    ISO: 'KI',
    ISO3: 'KIR',
    name: 'Kiribati',
    phone_code: '+686',
    emoji_flag: '🇰🇮',
  },
  {
    ISO: 'KP',
    ISO3: 'PRK',
    name: 'Corea del Norte',
    phone_code: '+850',
    emoji_flag: '🇰🇵',
  },
  {
    ISO: 'KR',
    ISO3: 'KOR',
    name: 'Corea del Sur',
    phone_code: '+82',
    emoji_flag: '🇰🇷',
  },
  {
    ISO: 'KW',
    ISO3: 'KWT',
    name: 'Kuwait',
    phone_code: '+965',
    emoji_flag: '🇰🇼',
  },
  {
    ISO: 'KG',
    ISO3: 'KGZ',
    name: 'Kirguistán',
    phone_code: '+996',
    emoji_flag: '🇰🇬',
  },
  {
    ISO: 'LA',
    ISO3: 'LAO',
    name: 'Laos',
    phone_code: '+856',
    emoji_flag: '🇱🇦',
  },
  {
    ISO: 'LV',
    ISO3: 'LVA',
    name: 'Letonia',
    phone_code: '+371',
    emoji_flag: '🇱🇻',
  },
  {
    ISO: 'LB',
    ISO3: 'LBN',
    name: 'Líbano',
    phone_code: '+961',
    emoji_flag: '🇱🇧',
  },
  {
    ISO: 'LS',
    ISO3: 'LSO',
    name: 'Lesoto',
    phone_code: '+266',
    emoji_flag: '🇱🇸',
  },
  {
    ISO: 'LR',
    ISO3: 'LBR',
    name: 'Liberia',
    phone_code: '+231',
    emoji_flag: '🇱🇷',
  },
  {
    ISO: 'LY',
    ISO3: 'LBY',
    name: 'Libia',
    phone_code: '+218',
    emoji_flag: '🇱🇾',
  },
  {
    ISO: 'LI',
    ISO3: 'LIE',
    name: 'Liechtenstein',
    phone_code: '+423',
    emoji_flag: '🇱🇮',
  },
  {
    ISO: 'LT',
    ISO3: 'LTU',
    name: 'Lituania',
    phone_code: '+370',
    emoji_flag: '🇱🇹',
  },
  {
    ISO: 'LU',
    ISO3: 'LUX',
    name: 'Luxemburgo',
    phone_code: '+352',
    emoji_flag: '🇱🇺',
  },
  {
    ISO: 'MO',
    ISO3: 'MAC',
    name: 'Macao',
    phone_code: '+853',
    emoji_flag: '🇲🇴',
  },
  {
    ISO: 'MK',
    ISO3: 'MKD',
    name: 'Macedonia del Norte',
    phone_code: '+389',
    emoji_flag: '🇲🇰',
  },
  {
    ISO: 'MG',
    ISO3: 'MDG',
    name: 'Madagascar',
    phone_code: '+261',
    emoji_flag: '🇲🇬',
  },
  {
    ISO: 'MW',
    ISO3: 'MWI',
    name: 'Malaui',
    phone_code: '+265',
    emoji_flag: '🇲🇼',
  },
  {
    ISO: 'MY',
    ISO3: 'MYS',
    name: 'Malasia',
    phone_code: '+60',
    emoji_flag: '🇲🇾',
  },
  {
    ISO: 'MV',
    ISO3: 'MDV',
    name: 'Maldivas',
    phone_code: '+960',
    emoji_flag: '🇲🇻',
  },
  {
    ISO: 'ML',
    ISO3: 'MLI',
    name: 'Mali',
    phone_code: '+223',
    emoji_flag: '🇲🇱',
  },
  {
    ISO: 'MT',
    ISO3: 'MLT',
    name: 'Malta',
    phone_code: '+356',
    emoji_flag: '🇲🇹',
  },
  {
    ISO: 'MH',
    ISO3: 'MHL',
    name: 'Islas Marshall',
    phone_code: '+692',
    emoji_flag: '🇲🇭',
  },
  {
    ISO: 'MQ',
    ISO3: 'MTQ',
    name: 'Martinica',
    phone_code: '+596',
    emoji_flag: '🇲🇶',
  },
  {
    ISO: 'MR',
    ISO3: 'MRT',
    name: 'Mauritania',
    phone_code: '+222',
    emoji_flag: '🇲🇷',
  },
  {
    ISO: 'MU',
    ISO3: 'MUS',
    name: 'Mauricio',
    phone_code: '+230',
    emoji_flag: '🇲🇺',
  },
  {
    ISO: 'YT',
    ISO3: 'MYT',
    name: 'Mayotte',
    phone_code: '+262',
    emoji_flag: '🇾🇹',
  },
  {
    ISO: 'MX',
    ISO3: 'MEX',
    name: 'México',
    phone_code: '+52',
    emoji_flag: '🇲🇽',
  },
  {
    ISO: 'FM',
    ISO3: 'FSM',
    name: 'Estados Federados de Micronesia',
    phone_code: '+691',
    emoji_flag: '🇫🇲',
  },
  {
    ISO: 'MD',
    ISO3: 'MDA',
    name: 'Moldavia',
    phone_code: '+373',
    emoji_flag: '🇲🇩',
  },
  {
    ISO: 'MC',
    ISO3: 'MCO',
    name: 'Mónaco',
    phone_code: '+377',
    emoji_flag: '🇲🇨',
  },
  {
    ISO: 'MN',
    ISO3: 'MNG',
    name: 'Mongolia',
    phone_code: '+976',
    emoji_flag: '🇲🇳',
  },
  {
    ISO: 'MS',
    ISO3: 'MSR',
    name: 'Montserrat',
    phone_code: '+1-664',
    emoji_flag: '🇲🇸',
  },
  {
    ISO: 'MA',
    ISO3: 'MAR',
    name: 'Marruecos',
    phone_code: '+212',
    emoji_flag: '🇲🇦',
  },
  {
    ISO: 'MZ',
    ISO3: 'MOZ',
    name: 'Mozambique',
    phone_code: '+258',
    emoji_flag: '🇲🇿',
  },
  {
    ISO: 'MM',
    ISO3: 'MMR',
    name: 'Myanmar',
    phone_code: '+95',
    emoji_flag: '🇲🇲',
  },
  {
    ISO: 'NA',
    ISO3: 'NAM',
    name: 'Namibia',
    phone_code: '+264',
    emoji_flag: '🇳🇦',
  },
  {
    ISO: 'NR',
    ISO3: 'NRU',
    name: 'Nauru',
    phone_code: '+674',
    emoji_flag: '🇳🇷',
  },
  {
    ISO: 'NP',
    ISO3: 'NPL',
    name: 'Nepal',
    phone_code: '+977',
    emoji_flag: '🇳🇵',
  },
  {
    ISO: 'NL',
    ISO3: 'NLD',
    name: 'Países Bajos',
    phone_code: '+31',
    emoji_flag: '🇳🇱',
  },
  {
    ISO: 'AN',
    ISO3: 'ANT',
    name: 'Antillas Neerlandesas',
    phone_code: '+599',
    emoji_flag: '',
  },
  {
    ISO: 'NC',
    ISO3: 'NCL',
    name: 'Nueva Caledonia',
    phone_code: '+687',
    emoji_flag: '🇳🇨',
  },
  {
    ISO: 'NZ',
    ISO3: 'NZL',
    name: 'Nueva Zelanda',
    phone_code: '+64',
    emoji_flag: '🇳🇿',
  },
  {
    ISO: 'NI',
    ISO3: 'NIC',
    name: 'Nicaragua',
    phone_code: '+505',
    emoji_flag: '🇳🇮',
  },
  {
    ISO: 'NE',
    ISO3: 'NER',
    name: 'Níger',
    phone_code: '+227',
    emoji_flag: '🇳🇪',
  },
  {
    ISO: 'NG',
    ISO3: 'NGA',
    name: 'Nigeria',
    phone_code: '+234',
    emoji_flag: '🇳🇬',
  },
  {
    ISO: 'NU',
    ISO3: 'NIU',
    name: 'Niue',
    phone_code: '+683',
    emoji_flag: '🇳🇺',
  },
  {
    ISO: 'NF',
    ISO3: 'NFK',
    name: 'Isla Norfolk',
    phone_code: '+672',
    emoji_flag: '🇳🇫',
  },
  {
    ISO: 'MP',
    ISO3: 'MNP',
    name: 'Islas Marianas del Norte',
    phone_code: '+1-670',
    emoji_flag: '🇲🇵',
  },
  {
    ISO: 'NO',
    ISO3: 'NOR',
    name: 'Noruega',
    phone_code: '+47',
    emoji_flag: '🇳🇴',
  },
  {
    ISO: 'OM',
    ISO3: 'OMN',
    name: 'Omán',
    phone_code: '+968',
    emoji_flag: '🇴🇲',
  },
  {
    ISO: 'PK',
    ISO3: 'PAK',
    name: 'Pakistán',
    phone_code: '+92',
    emoji_flag: '🇵🇰',
  },
  {
    ISO: 'PW',
    ISO3: 'PLW',
    name: 'Palaos',
    phone_code: '+680',
    emoji_flag: '🇵🇼',
  },
  {
    ISO: 'PS',
    ISO3: 'PSE',
    name: 'Territorio Palestino',
    phone_code: '+970',
    emoji_flag: '🇵🇸',
  },
  {
    ISO: 'PA',
    ISO3: 'PAN',
    name: 'Panamá',
    phone_code: '+507',
    emoji_flag: '🇵🇦',
  },
  {
    ISO: 'PG',
    ISO3: 'PNG',
    name: 'Papúa Nueva Guinea',
    phone_code: '+675',
    emoji_flag: '🇵🇬',
  },
  {
    ISO: 'PY',
    ISO3: 'PRY',
    name: 'Paraguay',
    phone_code: '+595',
    emoji_flag: '🇵🇾',
  },
  {
    ISO: 'PE',
    ISO3: 'PER',
    name: 'Perú',
    phone_code: '+51',
    emoji_flag: '🇵🇪',
  },
  {
    ISO: 'PH',
    ISO3: 'PHL',
    name: 'Filipinas',
    phone_code: '+63',
    emoji_flag: '🇵🇭',
  },
  {
    ISO: 'PN',
    ISO3: 'PCN',
    name: 'Islas Pitcairn',
    phone_code: '+870',
    emoji_flag: '🇵🇳',
  },
  {
    ISO: 'PL',
    ISO3: 'POL',
    name: 'Polonia',
    phone_code: '+48',
    emoji_flag: '🇵🇱',
  },
  {
    ISO: 'PT',
    ISO3: 'PRT',
    name: 'Portugal',
    phone_code: '+351',
    emoji_flag: '🇵🇹',
  },
  {
    ISO: 'PR',
    ISO3: 'PRI',
    name: 'Puerto Rico',
    phone_code: '+1-787',
    emoji_flag: '🇵🇷',
  },
  {
    ISO: 'QA',
    ISO3: 'QAT',
    name: 'Catar',
    phone_code: '+974',
    emoji_flag: '🇶🇦',
  },
  {
    ISO: 'RE',
    ISO3: 'REU',
    name: 'Reunión',
    phone_code: '+262',
    emoji_flag: '🇷🇪',
  },
  {
    ISO: 'RO',
    ISO3: 'ROU',
    name: 'Rumanía',
    phone_code: '+40',
    emoji_flag: '🇷🇴',
  },
  {
    ISO: 'RU',
    ISO3: 'RUS',
    name: 'Rusia',
    phone_code: '+7',
    emoji_flag: '🇷🇺',
  },
  {
    ISO: 'RW',
    ISO3: 'RWA',
    name: 'Ruanda',
    phone_code: '+250',
    emoji_flag: '🇷🇼',
  },
  {
    ISO: 'SH',
    ISO3: 'SHN',
    name: 'Santa Elena',
    phone_code: '+290',
    emoji_flag: '🇸🇭',
  },
  {
    ISO: 'KN',
    ISO3: 'KNA',
    name: 'San Cristóbal y Nieves',
    phone_code: '+1-869',
    emoji_flag: '🇰🇳',
  },
  {
    ISO: 'LC',
    ISO3: 'LCA',
    name: 'Santa Lucía',
    phone_code: '+1-758',
    emoji_flag: '🇱🇨',
  },
  {
    ISO: 'PM',
    ISO3: 'SPM',
    name: 'San Pedro y Miquelón',
    phone_code: '+508',
    emoji_flag: '🇵🇲',
  },
  {
    ISO: 'VC',
    ISO3: 'VCT',
    name: 'San Vicente y las Granadinas',
    phone_code: '+1-784',
    emoji_flag: '🇻🇨',
  },
  {
    ISO: 'WS',
    ISO3: 'WSM',
    name: 'Samoa',
    phone_code: '+685',
    emoji_flag: '🇼🇸',
  },
  {
    ISO: 'SM',
    ISO3: 'SMR',
    name: 'San Marino',
    phone_code: '+378',
    emoji_flag: '🇸🇲',
  },
  {
    ISO: 'ST',
    ISO3: 'STP',
    name: 'Santo Tomé y Príncipe',
    phone_code: '+239',
    emoji_flag: '🇸🇹',
  },
  {
    ISO: 'SA',
    ISO3: 'SAU',
    name: 'Arabia Saudita',
    phone_code: '+966',
    emoji_flag: '🇸🇦',
  },
  {
    ISO: 'SN',
    ISO3: 'SEN',
    name: 'Senegal',
    phone_code: '+221',
    emoji_flag: '🇸🇳',
  },
  {
    ISO: 'RS',
    ISO3: 'SRB',
    name: 'Serbia',
    phone_code: '+381',
    emoji_flag: '🇷🇸',
  },
  {
    ISO: 'SC',
    ISO3: 'SYC',
    name: 'Seychelles',
    phone_code: '+248',
    emoji_flag: '🇸🇨',
  },
  {
    ISO: 'SL',
    ISO3: 'SLE',
    name: 'Sierra Leona',
    phone_code: '+232',
    emoji_flag: '🇸🇱',
  },
  {
    ISO: 'SG',
    ISO3: 'SGP',
    name: 'Singapur',
    phone_code: '+65',
    emoji_flag: '🇸🇬',
  },
  {
    ISO: 'SK',
    ISO3: 'SVK',
    name: 'Eslovaquia',
    phone_code: '+421',
    emoji_flag: '🇸🇰',
  },
  {
    ISO: 'SI',
    ISO3: 'SVN',
    name: 'Eslovenia',
    phone_code: '+386',
    emoji_flag: '🇸🇮',
  },
  {
    ISO: 'SB',
    ISO3: 'SLB',
    name: 'Islas Salomón',
    phone_code: '+677',
    emoji_flag: '🇸🇧',
  },
  {
    ISO: 'SO',
    ISO3: 'SOM',
    name: 'Somalia',
    phone_code: '+252',
    emoji_flag: '🇸🇴',
  },
  {
    ISO: 'ZA',
    ISO3: 'ZAF',
    name: 'Sudáfrica',
    phone_code: '+27',
    emoji_flag: '🇿🇦',
  },
  {
    ISO: 'GS',
    ISO3: 'SGS',
    name: 'Islas Georgias del Sur y Sandwich del Sur',
    phone_code: '+500',
    emoji_flag: '🇬🇸',
  },
  {
    ISO: 'ES',
    ISO3: 'ESP',
    name: 'España',
    phone_code: '+34',
    emoji_flag: '🇪🇸',
  },
  {
    ISO: 'LK',
    ISO3: 'LKA',
    name: 'Sri Lanka',
    phone_code: '+94',
    emoji_flag: '🇱🇰',
  },
  {
    ISO: 'SD',
    ISO3: 'SDN',
    name: 'Sudán',
    phone_code: '+249',
    emoji_flag: '🇸🇩',
  },
  {
    ISO: 'SR',
    ISO3: 'SUR',
    name: 'Surinam',
    phone_code: '+597',
    emoji_flag: '🇸🇷',
  },
  {
    ISO: 'SJ',
    ISO3: 'SJM',
    name: 'Svalbard y Jan Mayen',
    phone_code: '+47',
    emoji_flag: '🇸🇯',
  },
  {
    ISO: 'SZ',
    ISO3: 'SWZ',
    name: 'Suazilandia (Eswatini)',
    phone_code: '+268',
    emoji_flag: '🇸🇿',
  },
  {
    ISO: 'SE',
    ISO3: 'SWE',
    name: 'Suecia',
    phone_code: '+46',
    emoji_flag: '🇸🇪',
  },
  {
    ISO: 'CH',
    ISO3: 'CHE',
    name: 'Suiza',
    phone_code: '+41',
    emoji_flag: '🇨🇭',
  },
  {
    ISO: 'SY',
    ISO3: 'SYR',
    name: 'República Árabe Siria',
    phone_code: '+963',
    emoji_flag: '🇸🇾',
  },
  {
    ISO: 'TW',
    ISO3: 'TWN',
    name: 'Taiwán (Provincia de China)',
    phone_code: '+886',
    emoji_flag: '🇹🇼',
  },
  {
    ISO: 'TJ',
    ISO3: 'TJK',
    name: 'Tayikistán',
    phone_code: '+992',
    emoji_flag: '🇹🇯',
  },
  {
    ISO: 'TZ',
    ISO3: 'TZA',
    name: 'Tanzania, República Unida de',
    phone_code: '+255',
    emoji_flag: '🇹🇿',
  },
  {
    ISO: 'TH',
    ISO3: 'THA',
    name: 'Tailandia',
    phone_code: '+66',
    emoji_flag: '🇹🇭',
  },
  {
    ISO: 'TL',
    ISO3: 'TLS',
    name: 'Timor-Leste',
    phone_code: '+670',
    emoji_flag: '🇹🇱',
  },
  {
    ISO: 'TG',
    ISO3: 'TGO',
    name: 'Togo',
    phone_code: '+228',
    emoji_flag: '🇹🇬',
  },
  {
    ISO: 'TK',
    ISO3: 'TKL',
    name: 'Tokelau',
    phone_code: '+690',
    emoji_flag: '🇹🇰',
  },
  {
    ISO: 'TO',
    ISO3: 'TON',
    name: 'Tonga',
    phone_code: '+676',
    emoji_flag: '🇹🇴',
  },
  {
    ISO: 'TT',
    ISO3: 'TTO',
    name: 'Trinidad y Tobago',
    phone_code: '+1-868',
    emoji_flag: '🇹🇹',
  },
  {
    ISO: 'TN',
    ISO3: 'TUN',
    name: 'Túnez',
    phone_code: '+216',
    emoji_flag: '🇹🇳',
  },
  {
    ISO: 'TR',
    ISO3: 'TUR',
    name: 'Turquía',
    phone_code: '+90',
    emoji_flag: '🇹🇷',
  },
  {
    ISO: 'TM',
    ISO3: 'TKM',
    name: 'Turkmenistán',
    phone_code: '+993',
    emoji_flag: '🇹🇲',
  },
  {
    ISO: 'TC',
    ISO3: 'TCA',
    name: 'Islas Turcas y Caicos',
    phone_code: '+1-649',
    emoji_flag: '🇹🇨',
  },
  {
    ISO: 'TV',
    ISO3: 'TUV',
    name: 'Tuvalu',
    phone_code: '+688',
    emoji_flag: '🇹🇻',
  },
  {
    ISO: 'UG',
    ISO3: 'UGA',
    name: 'Uganda',
    phone_code: '+256',
    emoji_flag: '🇺🇬',
  },
  {
    ISO: 'UA',
    ISO3: 'UKR',
    name: 'Ucrania',
    phone_code: '+380',
    emoji_flag: '🇺🇦',
  },
  {
    ISO: 'AE',
    ISO3: 'ARE',
    name: 'Emiratos Árabes Unidos',
    phone_code: '+971',
    emoji_flag: '🇦🇪',
  },
  {
    ISO: 'GB',
    ISO3: 'GBR',
    name: 'Reino Unido',
    phone_code: '+44',
    emoji_flag: '🇬🇧',
  },
  {
    ISO: 'US',
    ISO3: 'USA',
    name: 'Estados Unidos',
    phone_code: '+1',
    emoji_flag: '🇺🇸',
  },
  {
    ISO: 'UM',
    ISO3: 'UMI',
    name: 'Islas Ultramarinas Menores de Estados Unidos',
    phone_code: '+1',
    emoji_flag: '🇺🇲',
  },
  {
    ISO: 'UY',
    ISO3: 'URY',
    name: 'Uruguay',
    phone_code: '+598',
    emoji_flag: '🇺🇾',
  },
  {
    ISO: 'UZ',
    ISO3: 'UZB',
    name: 'Uzbekistán',
    phone_code: '+998',
    emoji_flag: '🇺🇿',
  },
  {
    ISO: 'VU',
    ISO3: 'VUT',
    name: 'Vanuatu',
    phone_code: '+678',
    emoji_flag: '🇻🇺',
  },
  {
    ISO: 'VE',
    ISO3: 'VEN',
    name: 'Venezuela, República Bolivariana de',
    phone_code: '+58',
    emoji_flag: '🇻🇪',
  },
  {
    ISO: 'VN',
    ISO3: 'VNM',
    name: 'Vietnam',
    phone_code: '+84',
    emoji_flag: '🇻🇳',
  },
  {
    ISO: 'VG',
    ISO3: 'VGB',
    name: 'Islas Vírgenes Británicas',
    phone_code: '+1-284',
    emoji_flag: '🇻🇬',
  },
  {
    ISO: 'VI',
    ISO3: 'VIR',
    name: 'Islas Vírgenes de los Estados Unidos',
    phone_code: '+1-340',
    emoji_flag: '🇻🇮',
  },
  {
    ISO: 'WF',
    ISO3: 'WLF',
    name: 'Wallis y Futuna',
    phone_code: '+681',
    emoji_flag: '🇼🇫',
  },
  {
    ISO: 'EH',
    ISO3: 'ESH',
    name: 'Sáhara Occidental',
    phone_code: '+212',
    emoji_flag: '🇪🇭',
  },
  {
    ISO: 'YE',
    ISO3: 'YEM',
    name: 'Yemen',
    phone_code: '+967',
    emoji_flag: '🇾🇪',
  },
  {
    ISO: 'ZM',
    ISO3: 'ZMB',
    name: 'Zambia',
    phone_code: '+260',
    emoji_flag: '🇿🇲',
  },
  {
    ISO: 'ZW',
    ISO3: 'ZWE',
    name: 'Zimbabue',
    phone_code: '+263',
    emoji_flag: '🇿🇼',
  },
  {
    ISO: 'ME',
    ISO3: 'MNE',
    name: 'Montenegro',
    phone_code: '+382',
    emoji_flag: '🇲🇪',
  },
  {
    ISO: 'XK',
    ISO3: 'XKX',
    name: 'Kosovo',
    phone_code: '+383',
    emoji_flag: '🇽🇰',
  },
  {
    ISO: 'AX',
    ISO3: 'ALA',
    name: 'Islas Åland',
    phone_code: '+358',
    emoji_flag: '🇦🇽',
  },
  {
    ISO: 'BQ',
    ISO3: 'BES',
    name: 'Bonaire, San Eustaquio y Saba',
    phone_code: '+599',
    emoji_flag: '🇧🇶',
  },
  {
    ISO: 'CW',
    ISO3: 'CUW',
    name: 'Curazao',
    phone_code: '+599',
    emoji_flag: '🇨🇼',
  },
  {
    ISO: 'GG',
    ISO3: 'GGY',
    name: 'Guernsey',
    phone_code: '+44',
    emoji_flag: '🇬🇬',
  },
  {
    ISO: 'IM',
    ISO3: 'IMN',
    name: 'Isla de Man',
    phone_code: '+44',
    emoji_flag: '🇮🇲',
  },
  {
    ISO: 'JE',
    ISO3: 'JEY',
    name: 'Jersey',
    phone_code: '+44',
    emoji_flag: '🇯🇪',
  },
  {
    ISO: 'BL',
    ISO3: 'BLM',
    name: 'San Bartolomé',
    phone_code: '+590',
    emoji_flag: '🇧🇱',
  },
  {
    ISO: 'MF',
    ISO3: 'MAF',
    name: 'San Martín (parte francesa)',
    phone_code: '+590',
    emoji_flag: '🇲🇫',
  },
  {
    ISO: 'SX',
    ISO3: 'SXM',
    name: 'Sint Maarten (parte neerlandesa)',
    phone_code: '+1-721',
    emoji_flag: '🇸🇽',
  },
  {
    ISO: 'SS',
    ISO3: 'SSD',
    name: 'Sudán del Sur',
    phone_code: '+211',
    emoji_flag: '🇸🇸',
  },
];
